# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonalnformationWindow(object):
    def setupUi(self, PersonalnformationWindow):
        PersonalnformationWindow.setObjectName("PersonalnformationWindow")
        PersonalnformationWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PersonalnformationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 390, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 300, 401, 41))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 390, 401, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 380, 211, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 210, 401, 41))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 470, 511, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 110, 401, 41))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        PersonalnformationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PersonalnformationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        PersonalnformationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PersonalnformationWindow)
        self.statusbar.setObjectName("statusbar")
        PersonalnformationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PersonalnformationWindow)
        QtCore.QMetaObject.connectSlotsByName(PersonalnformationWindow)

    def retranslateUi(self, PersonalnformationWindow):
        _translate = QtCore.QCoreApplication.translate
        PersonalnformationWindow.setWindowTitle(_translate("PersonalnformationWindow", "个人信息"))
        self.label.setText(_translate("PersonalnformationWindow", "学号："))
        self.label_2.setText(_translate("PersonalnformationWindow", "姓名："))
        self.label_3.setText(_translate("PersonalnformationWindow", "年龄："))
        self.label_4.setText(_translate("PersonalnformationWindow", "地址："))
        self.pushButton.setText(_translate("PersonalnformationWindow", "修改头像"))
        self.label_5.setText(_translate("PersonalnformationWindow", "tips: 可以修改个人信息"))
